
#Este es el Makefile para la compilacion del servidor y el cliente.
servidor: RemoteChatSrv.c
	gcc -o servidor RemoteChatSrv.c -lpthread
cliente: RemoteChatCli.c
	gcc -o cliente RemoteChatCli.c -lpthread


#Regla para eliminar el archivos creados por la compilación
clean:
	rm -f servidor cliente *.o
   
